export const elements = [
  { symbol: "H", name: "Hydrogen", weight: "1.00794", period: 1, group: 1 },
  { symbol: "He", name: "Helium", weight: "4.002602", period: 1, group: 18 },
  { symbol: "Li", name: "Lithium", weight: "6.941", period: 2, group: 1 },
  { symbol: "Be", name: "Beryllium", weight: "9.012182", period: 2, group: 2 },
  { symbol: "B", name: "Boron", weight: "10.811", period: 2, group: 13 },
  { symbol: "C", name: "Carbon", weight: "12.0107", period: 2, group: 14 },
  { symbol: "N", name: "Nitrogen", weight: "14.0067", period: 2, group: 15 },
  { symbol: "O", name: "Oxygen", weight: "15.9994", period: 2, group: 16 },
  { symbol: "F", name: "Fluorine", weight: "18.9984032", period: 2, group: 17 },
  { symbol: "Ne", name: "Neon", weight: "20.1797", period: 2, group: 18 },
  { symbol: "Na", name: "Sodium", weight: "22.98976...", period: 3, group: 1 },
  { symbol: "Mg", name: "Magnesium", weight: "24.305", period: 3, group: 2 },
  {
    symbol: "Al",
    name: "Aluminium",
    weight: "26.9815386",
    period: 3,
    group: 13,
  },
  { symbol: "Si", name: "Silicon", weight: "28.0855", period: 3, group: 14 },
  {
    symbol: "P",
    name: "Phosphorus",
    weight: "30.973762",
    period: 3,
    group: 15,
  },
  { symbol: "S", name: "Sulfur", weight: "32.065", period: 3, group: 16 },
  { symbol: "Cl", name: "Chlorine", weight: "35.453", period: 3, group: 17 },
  { symbol: "Ar", name: "Argon", weight: "39.948", period: 3, group: 18 },
  { symbol: "K", name: "Potassium", weight: "39.948", period: 4, group: 1 },
  { symbol: "Ca", name: "Calcium", weight: "40.078", period: 4, group: 2 },
  { symbol: "Sc", name: "Scandium", weight: "44.955912", period: 4, group: 3 },
  { symbol: "Ti", name: "Titanium", weight: "47.867", period: 4, group: 4 },
  { symbol: "V", name: "Vanadium", weight: "50.9415", period: 4, group: 5 },
  { symbol: "Cr", name: "Chromium", weight: "51.9961", period: 4, group: 6 },
  { symbol: "Mn", name: "Manganese", weight: "54.938045", period: 4, group: 7 },
  { symbol: "Fe", name: "Iron", weight: "55.845", period: 4, group: 8 },
  { symbol: "Co", name: "Cobalt", weight: "58.933195", period: 4, group: 9 },
  { symbol: "Ni", name: "Nickel", weight: "58.6934", period: 4, group: 10 },
  { symbol: "Cu", name: "Copper", weight: "63.546", period: 4, group: 11 },
  { symbol: "Zn", name: "Zinc", weight: "65.38", period: 4, group: 12 },
  { symbol: "Ga", name: "Gallium", weight: "69.723", period: 4, group: 13 },
  { symbol: "Ge", name: "Germanium", weight: "72.63", period: 4, group: 14 },
  { symbol: "As", name: "Arsenic", weight: "74.9216", period: 4, group: 15 },
  { symbol: "Se", name: "Selenium", weight: "78.96", period: 4, group: 16 },
  { symbol: "Br", name: "Bromine", weight: "79.904", period: 4, group: 17 },
  { symbol: "Kr", name: "Krypton", weight: "83.798", period: 4, group: 18 },
  { symbol: "Rb", name: "Rubidium", weight: "85.4678", period: 5, group: 1 },
  { symbol: "Sr", name: "Strontium", weight: "87.62", period: 5, group: 2 },
  { symbol: "Y", name: "Yttrium", weight: "88.90585", period: 5, group: 3 },
  { symbol: "Zr", name: "Zirconium", weight: "91.224", period: 5, group: 4 },
  { symbol: "Nb", name: "Niobium", weight: "92.90628", period: 5, group: 5 },
  { symbol: "Mo", name: "Molybdenum", weight: "95.96", period: 5, group: 6 },
  { symbol: "Tc", name: "Technetium", weight: "(98)", period: 5, group: 7 },
  { symbol: "Ru", name: "Ruthenium", weight: "101.07", period: 5, group: 8 },
  { symbol: "Rh", name: "Rhodium", weight: "102.9055", period: 5, group: 9 },
  { symbol: "Pd", name: "Palladium", weight: "106.42", period: 5, group: 10 },
  { symbol: "Ag", name: "Silver", weight: "107.8682", period: 5, group: 11 },
  { symbol: "Cd", name: "Cadmium", weight: "112.411", period: 5, group: 12 },
  { symbol: "In", name: "Indium", weight: "114.818", period: 5, group: 13 },
  { symbol: "Sn", name: "Tin", weight: "118.71", period: 5, group: 14 },
  { symbol: "Sb", name: "Antimony", weight: "121.76", period: 5, group: 15 },
  { symbol: "Te", name: "Tellurium", weight: "127.6", period: 5, group: 16 },
  { symbol: "I", name: "Iodine", weight: "126.90447", period: 5, group: 17 },
  { symbol: "Xe", name: "Xenon", weight: "131.293", period: 5, group: 18 },
  { symbol: "Cs", name: "Caesium", weight: "132.9054", period: 6, group: 1 },
  { symbol: "Ba", name: "Barium", weight: "132.9054", period: 6, group: 2 },
  { symbol: "La", name: "Lanthanum", weight: "138.90547", period: 6, group: 4 },
  { symbol: "Ce", name: "Cerium", weight: "140.116", period: 6, group: 5 },
  {
    symbol: "Pr",
    name: "Praseodymium",
    weight: "140.90765",
    period: 6,
    group: 6,
  },
  { symbol: "Nd", name: "Neodymium", weight: "144.242", period: 6, group: 7 },
  { symbol: "Pm", name: "Promethium", weight: "(145)", period: 6, group: 8 },
  { symbol: "Sm", name: "Samarium", weight: "150.36", period: 6, group: 9 },
  { symbol: "Eu", name: "Europium", weight: "151.964", period: 6, group: 10 },
  { symbol: "Gd", name: "Gadolinium", weight: "157.25", period: 6, group: 11 },
  { symbol: "Tb", name: "Terbium", weight: "158.92535", period: 6, group: 12 },
  { symbol: "Dy", name: "Dysprosium", weight: "162.5", period: 6, group: 13 },
  { symbol: "Ho", name: "Holmium", weight: "164.93032", period: 6, group: 14 },
  { symbol: "Er", name: "Erbium", weight: "167.259", period: 6, group: 15 },
  { symbol: "Tm", name: "Thulium", weight: "168.93421", period: 6, group: 16 },
  { symbol: "Yb", name: "Ytterbium", weight: "173.054", period: 6, group: 17 },
  { symbol: "Lu", name: "Lutetium", weight: "174.9668", period: 6, group: 18 },
  { symbol: "Hf", name: "Hafnium", weight: "178.49", period: 6, group: 4 },
  { symbol: "Ta", name: "Tantalum", weight: "180.94788", period: 6, group: 5 },
  { symbol: "W", name: "Tungsten", weight: "183.84", period: 6, group: 6 },
  { symbol: "Re", name: "Rhenium", weight: "186.207", period: 6, group: 7 },
  { symbol: "Os", name: "Osmium", weight: "190.23", period: 6, group: 8 },
  { symbol: "Ir", name: "Iridium", weight: "192.217", period: 6, group: 9 },
  { symbol: "Pt", name: "Platinum", weight: "195.084", period: 6, group: 10 },
  { symbol: "Au", name: "Gold", weight: "196.966569", period: 6, group: 11 },
  { symbol: "Hg", name: "Mercury", weight: "200.59", period: 6, group: 12 },
  { symbol: "Tl", name: "Thallium", weight: "204.3833", period: 6, group: 13 },
  { symbol: "Pb", name: "Lead", weight: "207.2", period: 6, group: 14 },
  { symbol: "Bi", name: "Bismuth", weight: "208.9804", period: 6, group: 15 },
  { symbol: "Po", name: "Polonium", weight: "(209)", period: 6, group: 16 },
  { symbol: "At", name: "Astatine", weight: "(210)", period: 6, group: 17 },
  { symbol: "Rn", name: "Radon", weight: "(222)", period: 6, group: 18 },
  { symbol: "Fr", name: "Francium", weight: "(223)", period: 7, group: 1 },
  { symbol: "Ra", name: "Radium", weight: "(226)", period: 7, group: 2 },
  { symbol: "Ac", name: "Actinium", weight: "(227)", period: 7, group: 4 },
  { symbol: "Th", name: "Thorium", weight: "232.03806", period: 7, group: 5 },
  {
    symbol: "Pa",
    name: "Protactinium",
    weight: "231.0588",
    period: 7,
    group: 6,
  },
  { symbol: "U", name: "Uranium", weight: "238.02891", period: 7, group: 7 },
  { symbol: "Np", name: "Neptunium", weight: "(237)", period: 7, group: 8 },
  { symbol: "Pu", name: "Plutonium", weight: "(244)", period: 7, group: 9 },
  { symbol: "Am", name: "Americium", weight: "(243)", period: 7, group: 10 },
  { symbol: "Cm", name: "Curium", weight: "(247)", period: 7, group: 11 },
  { symbol: "Bk", name: "Berkelium", weight: "(247)", period: 7, group: 12 },
  { symbol: "Cf", name: "Californium", weight: "(251)", period: 7, group: 13 },
  { symbol: "Es", name: "Einstenium", weight: "(252)", period: 7, group: 14 },
  { symbol: "Fm", name: "Fermium", weight: "(257)", period: 7, group: 15 },
  { symbol: "Md", name: "Mendelevium", weight: "(258)", period: 7, group: 16 },
  { symbol: "No", name: "Nobelium", weight: "(259)", period: 7, group: 17 },
  { symbol: "Lr", name: "Lawrencium", weight: "(262)", period: 7, group: 18 },
  { symbol: "Rf", name: "Rutherfordium", weight: "(267)", period: 7, group: 4 },
  { symbol: "Db", name: "Dubnium", weight: "(268)", period: 7, group: 5 },
  { symbol: "Sg", name: "Seaborgium", weight: "(271)", period: 7, group: 6 },
  { symbol: "Bh", name: "Bohrium", weight: "(272)", period: 7, group: 7 },
  { symbol: "Hs", name: "Hassium", weight: "(270)", period: 7, group: 8 },
  { symbol: "Mt", name: "Meitnerium", weight: "(276)", period: 7, group: 9 },
  { symbol: "Ds", name: "Darmstadium", weight: "(281)", period: 7, group: 10 },
  { symbol: "Rg", name: "Roentgenium", weight: "(280)", period: 7, group: 11 },
  { symbol: "Cn", name: "Copernicium", weight: "(285)", period: 7, group: 12 },
  { symbol: "Nh", name: "Nihonium", weight: "(286)", period: 7, group: 13 },
  { symbol: "Fl", name: "Flerovium", weight: "(289)", period: 7, group: 14 },
  { symbol: "Mc", name: "Moscovium", weight: "(290)", period: 7, group: 15 },
  { symbol: "Lv", name: "Livermorium", weight: "(293)", period: 7, group: 16 },
  { symbol: "Ts", name: "Tennessine", weight: "(294)", period: 7, group: 17 },
  { symbol: "Og", name: "Oganesson", weight: "(294)", period: 7, group: 18 },
];

const period1 = [
  { symbol: "H", name: "Hydrogen", weight: "1.00794", period: 1, group: 1 },
  { symbol: "He", name: "Helium", weight: "4.002602", period: 1, group: 18 },
];
const period2 = [
  { symbol: "Li", name: "Lithium", weight: "6.941", period: 2, group: 1 },
  { symbol: "Be", name: "Beryllium", weight: "9.012182", period: 2, group: 2 },
  { symbol: "B", name: "Boron", weight: "10.811", period: 2, group: 13 },
  { symbol: "C", name: "Carbon", weight: "12.0107", period: 2, group: 14 },
  { symbol: "N", name: "Nitrogen", weight: "14.0067", period: 2, group: 15 },
  { symbol: "O", name: "Oxygen", weight: "15.9994", period: 2, group: 16 },
  { symbol: "F", name: "Fluorine", weight: "18.9984032", period: 2, group: 17 },
  { symbol: "Ne", name: "Neon", weight: "20.1797", period: 2, group: 18 },
];
const period3 = [
  { symbol: "Na", name: "Sodium", weight: "22.98976...", period: 3, group: 1 },
  { symbol: "Mg", name: "Magnesium", weight: "24.305", period: 3, group: 2 },
  {
    symbol: "Al",
    name: "Aluminium",
    weight: "26.9815386",
    period: 3,
    group: 13,
  },
  { symbol: "Si", name: "Silicon", weight: "28.0855", period: 3, group: 14 },
  {
    symbol: "P",
    name: "Phosphorus",
    weight: "30.973762",
    period: 3,
    group: 15,
  },
  { symbol: "S", name: "Sulfur", weight: "32.065", period: 3, group: 16 },
  { symbol: "Cl", name: "Chlorine", weight: "35.453", period: 3, group: 17 },
  { symbol: "Ar", name: "Argon", weight: "39.948", period: 3, group: 18 },
];
const period4 = [
  { symbol: "K", name: "Potassium", weight: "39.948", period: 4, group: 1 },
  { symbol: "Ca", name: "Calcium", weight: "40.078", period: 4, group: 2 },
  { symbol: "Sc", name: "Scandium", weight: "44.955912", period: 4, group: 3 },
  { symbol: "Ti", name: "Titanium", weight: "47.867", period: 4, group: 4 },
  { symbol: "V", name: "Vanadium", weight: "50.9415", period: 4, group: 5 },
  { symbol: "Cr", name: "Chromium", weight: "51.9961", period: 4, group: 6 },
  { symbol: "Mn", name: "Manganese", weight: "54.938045", period: 4, group: 7 },
  { symbol: "Fe", name: "Iron", weight: "55.845", period: 4, group: 8 },
  { symbol: "Co", name: "Cobalt", weight: "58.933195", period: 4, group: 9 },
  { symbol: "Ni", name: "Nickel", weight: "58.6934", period: 4, group: 10 },
  { symbol: "Cu", name: "Copper", weight: "63.546", period: 4, group: 11 },
  { symbol: "Zn", name: "Zinc", weight: "65.38", period: 4, group: 12 },
  { symbol: "Ga", name: "Gallium", weight: "69.723", period: 4, group: 13 },
  { symbol: "Ge", name: "Germanium", weight: "72.63", period: 4, group: 14 },
  { symbol: "As", name: "Arsenic", weight: "74.9216", period: 4, group: 15 },
  { symbol: "Se", name: "Selenium", weight: "78.96", period: 4, group: 16 },
  { symbol: "Br", name: "Bromine", weight: "79.904", period: 4, group: 17 },
  { symbol: "Kr", name: "Krypton", weight: "83.798", period: 4, group: 18 },
];
const period5 = [
  { symbol: "Rb", name: "Rubidium", weight: "85.4678", period: 5, group: 1 },
  { symbol: "Sr", name: "Strontium", weight: "87.62", period: 5, group: 2 },
  { symbol: "Y", name: "Yttrium", weight: "88.90585", period: 5, group: 3 },
  { symbol: "Zr", name: "Zirconium", weight: "91.224", period: 5, group: 4 },
  { symbol: "Nb", name: "Niobium", weight: "92.90628", period: 5, group: 5 },
  { symbol: "Mo", name: "Molybdenum", weight: "95.96", period: 5, group: 6 },
  { symbol: "Tc", name: "Technetium", weight: "(98)", period: 5, group: 7 },
  { symbol: "Ru", name: "Ruthenium", weight: "101.07", period: 5, group: 8 },
  { symbol: "Rh", name: "Rhodium", weight: "102.9055", period: 5, group: 9 },
  { symbol: "Pd", name: "Palladium", weight: "106.42", period: 5, group: 10 },
  { symbol: "Ag", name: "Silver", weight: "107.8682", period: 5, group: 11 },
  { symbol: "Cd", name: "Cadmium", weight: "112.411", period: 5, group: 12 },
  { symbol: "In", name: "Indium", weight: "114.818", period: 5, group: 13 },
  { symbol: "Sn", name: "Tin", weight: "118.71", period: 5, group: 14 },
  { symbol: "Sb", name: "Antimony", weight: "121.76", period: 5, group: 15 },
  { symbol: "Te", name: "Tellurium", weight: "127.6", period: 5, group: 16 },
  { symbol: "I", name: "Iodine", weight: "126.90447", period: 5, group: 17 },
  { symbol: "Xe", name: "Xenon", weight: "131.293", period: 5, group: 18 },
];
const period6 = [
  { symbol: "Cs", name: "Caesium", weight: "132.9054", period: 6, group: 1 },
  { symbol: "Ba", name: "Barium", weight: "132.9054", period: 6, group: 2 },
  { symbol: "La", name: "Lanthanum", weight: "138.90547", period: 6, group: 4 },
  { symbol: "Ce", name: "Cerium", weight: "140.116", period: 6, group: 5 },
  {
    symbol: "Pr",
    name: "Praseodymium",
    weight: "140.90765",
    period: 6,
    group: 6,
  },
  { symbol: "Nd", name: "Neodymium", weight: "144.242", period: 6, group: 7 },
  { symbol: "Pm", name: "Promethium", weight: "(145)", period: 6, group: 8 },
  { symbol: "Sm", name: "Samarium", weight: "150.36", period: 6, group: 9 },
  { symbol: "Eu", name: "Europium", weight: "151.964", period: 6, group: 10 },
  { symbol: "Gd", name: "Gadolinium", weight: "157.25", period: 6, group: 11 },
  { symbol: "Tb", name: "Terbium", weight: "158.92535", period: 6, group: 12 },
  { symbol: "Dy", name: "Dysprosium", weight: "162.5", period: 6, group: 13 },
  { symbol: "Ho", name: "Holmium", weight: "164.93032", period: 6, group: 14 },
  { symbol: "Er", name: "Erbium", weight: "167.259", period: 6, group: 15 },
  { symbol: "Tm", name: "Thulium", weight: "168.93421", period: 6, group: 16 },
  { symbol: "Yb", name: "Ytterbium", weight: "173.054", period: 6, group: 17 },
  { symbol: "Lu", name: "Lutetium", weight: "174.9668", period: 6, group: 18 },
  { symbol: "Hf", name: "Hafnium", weight: "178.49", period: 6, group: 4 },
  { symbol: "Ta", name: "Tantalum", weight: "180.94788", period: 6, group: 5 },
  { symbol: "W", name: "Tungsten", weight: "183.84", period: 6, group: 6 },
  { symbol: "Re", name: "Rhenium", weight: "186.207", period: 6, group: 7 },
  { symbol: "Os", name: "Osmium", weight: "190.23", period: 6, group: 8 },
  { symbol: "Ir", name: "Iridium", weight: "192.217", period: 6, group: 9 },
  { symbol: "Pt", name: "Platinum", weight: "195.084", period: 6, group: 10 },
  { symbol: "Au", name: "Gold", weight: "196.966569", period: 6, group: 11 },
  { symbol: "Hg", name: "Mercury", weight: "200.59", period: 6, group: 12 },
  { symbol: "Tl", name: "Thallium", weight: "204.3833", period: 6, group: 13 },
  { symbol: "Pb", name: "Lead", weight: "207.2", period: 6, group: 14 },
  { symbol: "Bi", name: "Bismuth", weight: "208.9804", period: 6, group: 15 },
  { symbol: "Po", name: "Polonium", weight: "(209)", period: 6, group: 16 },
  { symbol: "At", name: "Astatine", weight: "(210)", period: 6, group: 17 },
  { symbol: "Rn", name: "Radon", weight: "(222)", period: 6, group: 18 },
];
const period7 = [
  { symbol: "Fr", name: "Francium", weight: "(223)", period: 7, group: 1 },
  { symbol: "Ra", name: "Radium", weight: "(226)", period: 7, group: 2 },
  { symbol: "Ac", name: "Actinium", weight: "(227)", period: 7, group: 4 },
  { symbol: "Th", name: "Thorium", weight: "232.03806", period: 7, group: 5 },
  {
    symbol: "Pa",
    name: "Protactinium",
    weight: "231.0588",
    period: 7,
    group: 6,
  },
  { symbol: "U", name: "Uranium", weight: "238.02891", period: 7, group: 7 },
  { symbol: "Np", name: "Neptunium", weight: "(237)", period: 7, group: 8 },
  { symbol: "Pu", name: "Plutonium", weight: "(244)", period: 7, group: 9 },
  { symbol: "Am", name: "Americium", weight: "(243)", period: 7, group: 10 },
  { symbol: "Cm", name: "Curium", weight: "(247)", period: 7, group: 11 },
  { symbol: "Bk", name: "Berkelium", weight: "(247)", period: 7, group: 12 },
  { symbol: "Cf", name: "Californium", weight: "(251)", period: 7, group: 13 },
  { symbol: "Es", name: "Einstenium", weight: "(252)", period: 7, group: 14 },
  { symbol: "Fm", name: "Fermium", weight: "(257)", period: 7, group: 15 },
  { symbol: "Md", name: "Mendelevium", weight: "(258)", period: 7, group: 16 },
  { symbol: "No", name: "Nobelium", weight: "(259)", period: 7, group: 17 },
  { symbol: "Lr", name: "Lawrencium", weight: "(262)", period: 7, group: 18 },
  { symbol: "Rf", name: "Rutherfordium", weight: "(267)", period: 7, group: 4 },
  { symbol: "Db", name: "Dubnium", weight: "(268)", period: 7, group: 5 },
  { symbol: "Sg", name: "Seaborgium", weight: "(271)", period: 7, group: 6 },
  { symbol: "Bh", name: "Bohrium", weight: "(272)", period: 7, group: 7 },
  { symbol: "Hs", name: "Hassium", weight: "(270)", period: 7, group: 8 },
  { symbol: "Mt", name: "Meitnerium", weight: "(276)", period: 7, group: 9 },
  { symbol: "Ds", name: "Darmstadium", weight: "(281)", period: 7, group: 10 },
  { symbol: "Rg", name: "Roentgenium", weight: "(280)", period: 7, group: 11 },
  { symbol: "Cn", name: "Copernicium", weight: "(285)", period: 7, group: 12 },
  { symbol: "Nh", name: "Nihonium", weight: "(286)", period: 7, group: 13 },
  { symbol: "Fl", name: "Flerovium", weight: "(289)", period: 7, group: 14 },
  { symbol: "Mc", name: "Moscovium", weight: "(290)", period: 7, group: 15 },
  { symbol: "Lv", name: "Livermorium", weight: "(293)", period: 7, group: 16 },
  { symbol: "Ts", name: "Tennessine", weight: "(294)", period: 7, group: 17 },
  { symbol: "Og", name: "Oganesson", weight: "(294)", period: 7, group: 18 },
];

export { period1, period2, period3, period4, period5, period6, period7 };
